name: Staging Deploy Claims
run-name: ${{ github.actor }} is deploying to ClaimClam Platform Staging  🚀
on:
  workflow_call:
    inputs:
      TaskCommand:
        required: true
        type: string
    secrets:
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      VARS:
        required: false
jobs:
  Run-Task:
    environment: staging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.0]
        node-version: [ 20 ]
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - name: Run Task Command
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          task ecr:login
          task ${{ inputs.TaskCommand }} ${{ secrets.VARS }}
