version: '3'
tasks:
    migrate:create:
        vars:
            NAME: "{{.NAME}}"
        cmds:
          - migrate create -ext sql -dir platform/sql/migrations/ -seq {{.NAME}}

    local:migrate:up:
        cmds:
          - migrate -path platform/sql/migrations/ -database "postgresql://admin:your_password@localhost:5438/traba?sslmode=disable" -verbose up

    local:migrate:down:
        cmds:
          - migrate -path platform/sql/migrations/ -database "postgresql://traba:password@localhost:5438/traba?sslmode=disable" -verbose down

    remote:migrate:up:
      vars:
        CONNECTION_STRING: "{{.CONNECTION_STRING}}"
      cmds:
        - migrate -path platform/sql/migrations/ -database "{{.CONNECTION_STRING}}" -verbose up

    remote:migrate:down:
      vars:
        CONNECTION_STRING: "{{.CONNECTION_STRING}}"
      cmds:
        - migrate -path platform/sql/migrations/ -database "{{.CONNECTION_STRING}}" -verbose down

    local:seed:db:
      desc: Seed the database with a local SQL file
      cmds:
        - |
          cat platform/sql/seed/seed-db.sql | docker exec -i -e PGPASSWORD=your_password fullstack-traba-copy-cat-postgres-1 psql -U admin -d traba
