name: Staging Deploy Frontend
run-name: ${{ github.actor }} is deploying to ClaimClam Platform Staging  🚀
on:
  push:
    branches:
      - main
    paths:
      - frontend/** 
jobs:
  Deploy-FE:
    uses: ./.github/workflows/__task_staging.yml
    with:
      TaskCommand: deploy:fe:staging
    secrets: # Add this section
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
